# 📄 /deploy/docker-compose.yml
version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports: [ "9000:9000", "9001:9001" ]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  gateway:
    image: php:8.2-fpm-alpine
    volumes:
      - ../gateway:/var/www/html
    working_dir: /var/www/html
    expose: [ "8080" ]
    depends_on: [ redis ]

  panel:
    build: ../panel
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports: [ "8443:443" ]
    volumes:
      - ../deploy/nginx/conf.d:/etc/nginx/conf.d
      - ../deploy/nginx/certs:/etc/nginx/certs
      - ../gateway:/var/www/html
    depends_on: [ gateway, panel ]
    restart: unless-stopped

volumes:
  minio-data:
