version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  gateway:
    image: php:8.2-fpm-alpine
    volumes:
      - ../gateway:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis
    expose:
      - "8080"

  panel:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../panel:/app
    command: ["sh", "-c", "npm install && npm run dev"]
    expose:
      - "5173"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8443:443"
    volumes:
      - ../deploy/nginx/conf.d:/etc/nginx/conf.d
      - ../deploy/nginx/certs:/etc/nginx/certs
      - ../gateway:/var/www/html
      - ../panel/dist:/var/www/panel
    depends_on:
      - gateway
      - panel
    restart: unless-stopped

volumes:
  minio-data:
