# 📄 /.github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - "6379:6379"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker services (gateway & panel)
        run: |
          docker compose -f deploy/docker-compose.yml build

      - name: Laravel Pint (Code Style)
        run: |
          docker run --rm -v ${{ github.workspace }}/gateway:/app -w /app laravelsail/php82-composer:latest \
          bash -c "composer global require laravel/pint && ~/.composer/vendor/bin/pint"

      - name: Vite Lint (ESLint)
        run: |
          docker run --rm -v ${{ github.workspace }}/panel:/app -w /app node:20-alpine \
          sh -c "npm install && npm run lint || true"
