# 📄 /.github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Laravel Gateway
        run: docker build -f deploy/docker-compose.yml .

      - name: Laravel Pint (Code Style)
        run: |
          docker run --rm -v $PWD/gateway:/app -w /app laravelsail/php82-composer:latest \
          bash -c "composer global require laravel/pint && ~/.composer/vendor/bin/pint"
